Module6 task2
htmlacademy-javascript/871783-kekstagram-21 pull request #10
Opened 2020-10-16 21:36 UTC by aquamarya

2020-10-17 10:16 UTC, Shv-sergey70 requested changes

2020-10-17 10:16 UTC, Shv-sergey70 commented on js/backend.js
> +  const URL_POST = `https://21.javascript.pages.academy/kekstagram`;
Стоит создать перечисление

2020-10-17 10:16 UTC, Shv-sergey70 commented on js/backend.js
> +    });
Обработчики нигде не снимаются после закрытия сообщения. Это значит что по-прежнему будут отлавливаться все mouseup и keydown, так быть не должно

2020-10-17 12:54 UTC, aquamarya commented on js/backend.js
> +  const URL_POST = `https://21.javascript.pages.academy/kekstagram`;
Создала

2020-10-17 16:54 UTC, aquamarya commented on js/backend.js
> +    });
удалила их через removeMessage

2020-10-18 08:48 UTC, Shv-sergey70 requested changes

2020-10-18 08:48 UTC, Shv-sergey70 commented on js/backend.js
> +  };
Проблема в том, что ты пытаешься снять обработчик `successHandler`, хотя на документ ты его нигде не навешивала. В данном случае, надо сделать обработчики НЕ анонимными функциями и тогда получится их снять

```
const renderMessage = (message, type) => {
    mainBlock.appendChild(message);

    const closeButton = mainBlock.querySelector(`.${type}__button`);
    const popup = mainBlock.querySelector(`.${type}`);
    popup.style.zIndex = ZET_INDEX;

    const removeMessage = () => {
      mainBlock.removeChild(message);
      document.removeEventListener(`keydown`, onDocumentKeydown);
      document.removeEventListener(`mouseup`, successHandler);
    };

    const onDocumentKeydown = (evt) => {
      if (evt.key === window.util.ESC_KEY) {
        removeMessage();
      }
    };

    closeButton.addEventListener(`click`, () => {
      removeMessage();
    });

    document.addEventListener(`keydown`, onDocumentKeydown);
    document.addEventListener(`mouseup`, (evt) => { // тут также чтобы удалить обработчик - он не должен быть анонимной функцией
      const target = evt.target.closest(`.${type}__inner`);
      if (!target) {
        removeMessage();
      }
    });
  };
```

2020-10-18 12:23 UTC, aquamarya commented on js/backend.js
> +  };
исправила

2020-10-19 09:56 UTC, merged