Module7 task1
htmlacademy-javascript/871783-kekstagram-21 pull request #11
Opened 2020-10-22 20:17 UTC by aquamarya

2020-10-23 12:29 UTC, Shv-sergey70 commented on js/sorting.js
> +  const usersPhotos = [];
Так массив же всегда пустой?

2020-10-23 17:33 UTC, Shv-sergey70 commented on js/gallery.js
> +    createPicturesList,
Тут стоит написать так:
```
window.gallery = {
    createCommentsFragment,
    createPicturesList,
    usersPhotos: [] // потом переопределится
  };
```

2020-10-23 17:33 UTC, Shv-sergey70 commented on js/gallery.js
> +    window.gallery = {
Это действие здесь лишнее. Можно так:
```
  // window.backend.load(createPicturesList, window.backend.loadErrorHandler);
  window.backend.load((photos) => {
    createPicturesList(photos);
    window.gallery.usersPhotos = photos;;
  }, window.backend.loadErrorHandler);
```

2020-10-23 17:33 UTC, Shv-sergey70 commented on js/sorting.js
> +    }
Висит страница из-за этого цикла. Он бесконечный

2020-10-24 11:29 UTC, Shv-sergey70 requested changes

2020-10-24 11:29 UTC, Shv-sergey70 commented on js/sorting.js
> +  };
```
  const removePhotos = () => {
    document.querySelectorAll(`.picture`).forEach((photo) => {
      photo.remove();
    });
  };
```

2020-10-24 11:29 UTC, Shv-sergey70 commented on js/sorting.js
> +  const removePhotos = () => {
Странно что функция по удалению фотографий находится в модуле `sorting`, ведь модуль должен отвечать только за сортировку. Следует переместить эту функцию в релевантный модуль

2020-10-24 11:29 UTC, Shv-sergey70 commented on js/sorting.js
> +  };
```
const changeActiveFilters = (filterButton) => {
    imgFiltersElement
      .querySelector(`.img-filters__button--active`)
      .classList
      .remove(`img-filters__button--active`);
    filterButton.classList.add(`img-filters__button--active`);
  };
```

2020-10-24 11:29 UTC, Shv-sergey70 commented on js/sorting.js
> +  };
Можно так:
```
  const sortPhotosByComments = (comments) => {
    return comments.sort((first, second) => second.comments.length - first.comments.length);
  };
```
Попробуй разобраться почему это работает (в документации метода `sort` есть примеры)

2020-10-24 11:29 UTC, Shv-sergey70 commented on js/sorting.js
> +  };
Можно даже сразу так:
```
  const getDiscussedPhotos = () => {
    const discussedPhotos = window.gallery.usersPhotos
      .slice()
      .sort((first, second) => second.comments.length - first.comments.length);

    window.gallery.createPicturesList(discussedPhotos);
  };
```

2020-10-24 11:29 UTC, Shv-sergey70 commented on js/sorting.js
> +        getDefaultPhotos();
Сейчас внутри каждой функции вызывает метод `window.gallery.createPicturesList` - это дублирование кода. Возвращай из функций только сортированный массив, и уже один раз в текущем методы вызывай `window.gallery.createPicturesList`

2020-10-24 11:29 UTC, Shv-sergey70 commented on js/util.js
> +  const shufflePhotos = (array) => {
Более удачное название вместо `array` -> `items`

2020-10-24 12:15 UTC, aquamarya commented on js/sorting.js
> +  const removePhotos = () => {
перенесла в gallery

2020-10-24 13:36 UTC, aquamarya commented on js/sorting.js
> +        getDefaultPhotos();
const filterClickHandler = window.util.debounce((evt) => {
    changeActiveFilters(evt.target);
    window.gallery.removePhotos();
    switch (evt.target) {
      case filtersDefault :
        window.gallery.createPicturesList(getDefaultPhotos());
        break;
      case filtersRandom:
        window.gallery.createPicturesList(getRandomPhotos());
        break;
      case filtersDiscussed:
        window.gallery.createPicturesList(getDiscussedPhotos());
        break;
      default:
        getDefaultPhotos();
    }
  });

так перенесла, но не понимаю, как быть с defalt, если тоже обернуть в createPicturesList, перестает переключаться

2020-10-24 18:22 UTC, Shv-sergey70 commented on js/sorting.js
> +  });
```
const filterClickHandler = window.util.debounce((evt) => {
    changeActiveFilters(evt.target);
    window.gallery.removePhotos();
    let sortedPhotos = [];

    switch (evt.target) {
      case filtersDefault :
        sortedPhotos = getDefaultPhotos();
        break;
      case filtersRandom:
        sortedPhotos = getRandomPhotos();
        break;
      case filtersDiscussed:
        sortedPhotos = getDiscussedPhotos();
        break;
      default:
        sortedPhotos = getDefaultPhotos();
    }

    window.gallery.createPicturesList(sortedPhotos);
  });
```
Я имел в виду так вынести и не дублировать `window.gallery.createPicturesList`

2020-10-24 18:22 UTC, Shv-sergey70 commented on js/sorting.js
> +      case filtersDiscussed:
В case стоит сравнивать только ID нужных фильтров. То есть не через дом-элементы, ведь тогда не придется их и искать

2020-10-24 18:22 UTC, Shv-sergey70 commented on js/sorting.js
> +  };
```
const getDefaultPhotos = () => window.gallery.usersPhotos;
```

2020-10-24 18:39 UTC, aquamarya commented on js/sorting.js
> +      case filtersDiscussed:
ok

2020-10-25 07:53 UTC, merged