Module3 task1
htmlacademy-javascript/871783-kekstagram-21 pull request #3
Opened 2020-09-24 17:15 UTC by aquamarya

2020-09-25 03:09 UTC, Shv-sergey70 requested changes

2020-09-25 03:09 UTC, Shv-sergey70 commented on js/main.js
> +const getRandomIntInclusive = function (min, max) {
Попробуй использовать везде синтаксис стрелочных функций

2020-09-25 03:09 UTC, Shv-sergey70 commented on js/main.js
> +    comments[i] = {
Можно так, либо не привязываясь к переменной `i`, 
```
comments.push({объект})
```

2020-09-25 03:09 UTC, Shv-sergey70 commented on js/main.js
> +  pictureElement.querySelector('.picture__comments').textContent = picture.comments;
Количество комментариев сейчас не отображается. Может нужно `length`?

2020-09-25 03:09 UTC, Shv-sergey70 commented on js/main.js
> +const MAX_COMMENTS_AMOUNT = 6;
Несколько констант объединенных по смыслу стоит выносить в перечисление. Пример оформления есть тут:
https://up.htmlacademy.ru/javascript/21/criteries#basic

2020-09-25 03:35 UTC, Shv-sergey70 commented on js/main.js
> +const getRandomIntInclusive = function (min, max) {
Например было так:
```
const getRandomArrayElement = function (array) {
  return array[getRandomIntInclusive(0, array.length - 1)];
};
```
Можно сделать так (если из функции только что-то возвращается):
```
const getRandomArrayElement = (array) => array[getRandomIntInclusive(0, array.length - 1)];
```
Либо так, если есть дополнительный код:
```
const getRandomIntInclusive = (min, max) => {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
};
```

2020-09-25 04:31 UTC, aquamarya commented on js/main.js
> +const getRandomIntInclusive = function (min, max) {
Переделала пока только эту функцию, остальные вроде слишком громоздкие для стрелочных.

2020-09-25 07:52 UTC, Shv-sergey70 commented on js/main.js
> +      likes: getRandomIntInclusive(likesAmount),
Тут по-прежнему нужно передавать 2 параметра:
`getRandomIntInclusive(likesAmount.MIN_LIKES, likesAmount.MAX_LIKES)`

2020-09-26 05:19 UTC, Shv-sergey70 requested changes
Сейчас у каждой картинки по 0 комментариев. Надо это поправить

2020-09-26 05:19 UTC, Shv-sergey70 commented on js/main.js
> +};
Перечисление должно начинаться с большой буквы, в критериях это есть.
В свойствах перечисления не нужно дублировать его название. В этом то его и суть, ты задаешь ключевое слово перечисления и внутри отличающиеся части:
```
const CommentsAmount = {
  MIN: 0,
  MAX: 6,
};
```

2020-09-26 05:19 UTC, Shv-sergey70 commented on js/main.js
> +};
Тут то же что и выше

2020-09-26 05:19 UTC, Shv-sergey70 commented on js/main.js
> +      comments: createComments(getRandomIntInclusive(commentsAmount.MIN_COMMENTS_AMOUNT, commentsAmount.MAX_COMMENTS_AMOUNT))
В `createComments` ты передаешь на вход число, но в самой функции работаешь с ним как с массивом.

2020-09-26 05:19 UTC, Shv-sergey70 commented on js/main.js
> +const createComments = (commentsArray) => {
`commentsArray` тут число или массив?

2020-09-26 08:19 UTC, aquamarya commented on js/main.js
> +};
Исправила

2020-09-26 13:05 UTC, Shv-sergey70 requested changes

2020-09-26 13:05 UTC, Shv-sergey70 commented on js/main.js
> +      avatar: 'img/avatar-' + getRandomIntInclusive(AvatarsAmount) + '.svg',
`getRandomIntInclusive` ожидает 2 числовых параметра. Сейчас ты передаешь туда объект. 
Это должно выглядеть так:
`getRandomIntInclusive(AvatarsAmount.MIN, AvatarsAmount.MAX)`

2020-09-26 13:05 UTC, Shv-sergey70 commented on js/main.js
> +      avatar: 'img/avatar-' + getRandomIntInclusive(AvatarsAmount) + '.svg',
Вместо конкатенации удобнее использовать шаблонные строки, код становится более читаемым. Попробуй использовать их всегда:
```
`img/avatar-${getRandomIntInclusive(AvatarsAmount.MIN, AvatarsAmount.MAX)}.svg`,
```

2020-09-26 13:05 UTC, Shv-sergey70 commented on js/main.js
> +      url: 'photos/' + (i + 1) + '.jpg',
Тут тоже можно использовать шаблонные строки вместо конкатенации

2020-09-26 13:05 UTC, Shv-sergey70 commented on js/main.js
> +const picturesTemplate = document.querySelector(`#picture`).content.querySelector(`.picture`);
Раз тут используешь бэктики, используй их везде, на всех строках

2020-09-26 13:21 UTC, aquamarya commented on js/main.js
> +const createComments = (commentsList) => {
ok

2020-09-26 13:22 UTC, aquamarya commented on js/main.js
> +const picturesTemplate = document.querySelector(`#picture`).content.querySelector(`.picture`);
Лучше  я везде одиночные кавычки буду использовать, поправила.

2020-09-26 15:38 UTC, merged