Module4 task1
htmlacademy-javascript/871783-kekstagram-21 pull request #5
Opened 2020-10-03 19:08 UTC by aquamarya

2020-10-04 09:57 UTC, Shv-sergey70 requested changes
Задай начальное значение в 100% прямо в разметке в `value`, так как изначально изображение отображается в полном размере:
![Снимок экрана 2020-10-04 в 12 46 20](https://user-images.githubusercontent.com/35741647/95012230-ab34c280-063f-11eb-8b7e-2ec18c90ec53.png)

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +});
Это действие не нужно. Клика достаточно, чтобы было закрытие по `ENTER`.
__Особенностью работы элементов таких как button, a, является то, что на них срабатывает событие click при нажатии клавиши Enter. Поэтому для таких элементов обрабатывать отдельно события клавиатуры необязательно.__

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +  viewPhotoItem.style.transform = `$scale(${newValue / 100})`;
Знак доллара перед `scale` лишний

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +  editScaleValue.value = newValue + `%`;
Используй вставку переменной в шаблонную строку, вместо конкатенации

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +const smallerButtonClickHandler = () => {
Обрати внимание, что код в `smallerButtonClickHandler` и `biggerButtonClickHandler` очень сильно похож, разница буквально в одном знаке. И не думаю, что тебе будет нужна функция `getScaleValue `

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +}
Попробуй добавить обработчики с помощью `forEach`, получится более красивый и лаконичный код

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +};
Если функция только что-то возвращает, можно писать без фигурных скобок и слова `return`. Посмотри короткий синтаксис стрелочных функций

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +  let warningMessage = ``;
Эта переменная тебе не нужна

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +      return warningMessage;
Во всех `return`, сразу возвращай соответствующую строку, без присваиваний в переменную:
```
return `хэш-тег начинается с символа # (решётка)`;
```

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +  const hashtags = hashtagsInput.value.toLowerCase().split(``);
Можно получить значение из `evt`:
```
evt.target.value.toLowerCase().split(``);
```

2020-10-04 09:57 UTC, Shv-sergey70 commented on js/main.js
> +  const hashtags = hashtagsInput.value.toLowerCase().split(``);
А разве тебе не по пробелу надо делать `split`? То есть:
```
.split(` `)
```

2020-10-04 13:36 UTC, aquamarya commented on js/main.js
> +}
effectsItems.forEach((effectsItem) => {
  effectsItem.addEventListener(`click`, filterChangeHandler);
});
как-то у меня не очень красиво и лаконично выходит

2020-10-04 13:36 UTC, aquamarya commented on js/main.js
> +};
переделала

2020-10-04 13:37 UTC, aquamarya commented on js/main.js
> +  const hashtags = hashtagsInput.value.toLowerCase().split(``);
проглядела

2020-10-04 13:38 UTC, aquamarya commented on js/main.js
> +const smallerButtonClickHandler = () => {
попробовала склеить в один, но тоже громоздко вышло и чего-то не хватает
const buttonClickHandler = (evt) => {
  const target = evt.target.closest(`button`);
  if (!target) {
    return;
  }
  const currentScaleValue = getScaleValue();
  let newValue;
  if (target === scaleSmallerButton) {
    if (editScaleValue > ScaleValue.MIN) {
      newValue = getScaleRange(currentScaleValue - SCALE_STEP);
    }
  }
  if (target === scaleBiggerButton) {
    if (editScaleValue < ScaleValue.MAX) {
      newValue = getScaleRange(currentScaleValue + SCALE_STEP);
    }
  }
  viewPhotoItem.style.transform = `scale(${newValue / 100})`;
  editScaleValue.value = `${newValue}%`;
};

2020-10-04 13:39 UTC, aquamarya commented on js/main.js
> +});
ок

2020-10-06 06:05 UTC, Shv-sergey70 requested changes
Проверь что форма правильно отправляется, с корректными данными

2020-10-06 06:05 UTC, Shv-sergey70 commented on js/main.js
> +const smallerButtonClickHandler = () => {
Попробуй тогда так:
```
const smallerButtonClickHandler = () => {
  calculateScale(getScaleValue() - SCALE_STEP);
};

const calculateScale = (newValue) => {
  const newScaleValue = getScaleRange(newValue);
  editScaleValue.value = `${newScaleValue}%`;
  viewPhotoItem.style.transform = `scale(${newScaleValue / 100})`;
};

const biggerButtonClickHandler = () => {
  calculateScale(getScaleValue() + SCALE_STEP);
};
```

2020-10-06 06:05 UTC, Shv-sergey70 commented on js/main.js
> +  return ` `;
Если все ок нужно возвращать пустую строку. Сейчас есть пробел. Пустая строка выглядит так:
```
``
```

2020-10-06 06:23 UTC, Shv-sergey70 requested changes

2020-10-06 06:23 UTC, Shv-sergey70 commented on js/main.js
> +  switch (currentFilter.id) {
~~Переменная `currentFilter ` используется только в одном месте, поэтому можно сразу так:
`switch (evt.target.value.id)`~~
Это работать правильно не может в `evt.target.value` - значение(строка), а ты потом пытаешь вызывать от него ID.
Можешь попробовать вывести в консоль `evt.target.value` перед `switch` и убедишься в этом

2020-10-06 06:23 UTC, Shv-sergey70 commented on js/main.js
> +});
Можно и стоит писать сразу так:
```
document.querySelectorAll(`.effects__radio`).forEach((effectsItem) => {
  effectsItem.addEventListener(`click`, filterChangeHandler);
});
```
Так как переменная `effectsItems` используется только в одном месте

2020-10-06 06:23 UTC, Shv-sergey70 commented on js/main.js
> +  editPhotoItem.addEventListener(`change`, filterChangeHandler);
А зачем на оверлей вешать обработчик на изменение фильтра?

2020-10-06 06:23 UTC, Shv-sergey70 commented on js/main.js
> +  }
Попробуй здесь использовать `forEach`

2020-10-06 06:23 UTC, Shv-sergey70 commented on js/main.js
> +};
Функция используется в одном месте и состоит из 1 строки - такая функция бесполезна

2020-10-06 06:23 UTC, Shv-sergey70 commented on js/main.js
> +      viewPhotoItem.classList.add(`effects__preview--none`);
Этот код отличается от остальный case только тем, что прячет эффект бар, вместо показа. Поэтому стоит все же привести к единому виду:
```
const applyFilter = (effect, showEffectBar = true) => {
  if (showEffectBar) {
    renderEffectBar();
  } else {
    hideEffect();
  }

  removeEffect();
  viewPhotoItem.classList.add(effect);
};

const filterChangeHandler = (evt) => {
  switch (evt.target.id) {
    case `effect-none`:
      applyFilter(`effects__preview--none`, false);
      break;
    case `effect-chrome`:
      applyFilter(`effects__preview--chrome`);
      break;
    case `effect-sepia`:
      applyFilter(`effects__preview--sepia`);
      break;
    case `effect-marvin`:
      applyFilter(`effects__preview--marvin`);
      break;
    case `effect-phobos`:
      applyFilter(`effects__preview--phobos`);
      break;
    case `effect-heat`:
      applyFilter(`effects__preview--heat`);
      break;
  }
};
```

2020-10-06 06:25 UTC, Shv-sergey70 commented on js/main.js
> +}
Это лучше, чем вручную делать итерации через создание переменной `i`

2020-10-06 17:13 UTC, aquamarya commented on js/main.js
> +};
сделала так

2020-10-06 17:13 UTC, aquamarya commented on js/main.js
> +});
удалила

2020-10-06 17:28 UTC, aquamarya commented on js/main.js
> +      viewPhotoItem.classList.add(`effects__preview--none`);
ок, спасибо

2020-10-06 18:09 UTC, aquamarya commented on js/main.js
> +    } else if (hashtags[i].length < HashtagsLength.MIN) {
убрала

2020-10-06 18:14 UTC, aquamarya commented on js/main.js
> +  editPhotoItem.addEventListener(`change`, filterChangeHandler);
уже не помню)
убрала

2020-10-06 18:25 UTC, aquamarya commented on js/main.js
> +};
удалила, код переместила в applyFilter

2020-10-07 08:36 UTC, merged